src/Teleoffice/ViewModels/Role/CreateViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Teleoffice.ViewModels.Role
{
    public class CreateViewModel
    {
    }
}

src/Teleoffice/ViewModels/Role/Roleuser.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Teleoffice.ViewModels.Role
{
    public class Roleuser
    {
        public String Id { get; set; }
        public String FName { get; set; }
        public String LName { get; set; }
        public String Email { get; set; }
        public String Role { get; set; }


    }
}

src/Teleoffice/Controllers/ManageUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Teleoffice.Models;
using System.Dynamic;
using Teleoffice.ViewModels.Role;
using System.Diagnostics;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Data.Entity;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Authorization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Teleoffice.Controllers
{
    
    public class ManageUserController : Controller
    {
        private ApplicationDbContext context;

        public ManageUserController(ApplicationDbContext _context)
        {
            context = _context;
        }

        // GET: /<controller>/
        [Authorize(Roles = "Administrator")]
        public IActionResult Index()
        {
            //dynamic dy = new ExpandoObject();
            var  users = context.Users.OrderBy(u => u.UserName).ToArray();
            var userrole = (from a in context.Roles
                            join ft in context.UserRoles on a.Id equals ft.RoleId
                            join z in context.Users on ft.UserId equals z.Id
                            select new Roleuser { FName = z.FirstName, LName = z.LastName, Email = z.Email, Role = a.Name, Id = z.Id }).ToList();

            //dy.role = (from xt in context.UserRoles
            //            join a in context.Users on xt.UserId equals a.Id 
            //             from t in context.UserRoles.DefaultIfEmpty()
            //             select new Roleuser { FName = a.FirstName, LName = a.LastName, Email = a.Email, Role = null, Id = a.Id }).ToList();
            return View(userrole);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult UserRoles(String id)
        {
            dynamic vm = new ExpandoObject();
            //context.Users.Include(r => r.Roles)
            vm.user = context.Users.Where(u => u.Id == id)
                .Single();
            //var rolemanager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            var urs = context.UserRoles.Where(ur => ur.UserId == id).ToArray();
            List<IdentityRole> roles = new List<IdentityRole>();
            IdentityRole role;
            foreach (var ur in urs)
            {
                role = context.Roles.Where(r => r.Id == ur.RoleId).Single();
                roles.Add(role);
            }
            vm.userroles = roles;
            return View(vm);
        }

        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public IActionResult AddUserRole(String id)
        {
            dynamic vm = new ExpandoObject();
            vm.user = context.Users.Where(u => u.Id == id)
                .Single();
            vm.roles = context.Roles.OrderBy(c => c.Name).ToArray();
            return View(vm);
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public IActionResult AddUserRole(IdentityUserRole<String> userrole)
        {
            if (ModelState.IsValid)
            {
                context.UserRoles.Add(userrole);
                context.SaveChanges();
                return RedirectToAction("UserRoles", new { id = userrole.UserId });
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult DeleteUserRole(String id, String roleid)
        {
            var userrole = context.UserRoles.Where(u => u.UserId == id & u.RoleId == roleid).Single();
            context.UserRoles.Remove(userrole);
            context.SaveChanges();
            return RedirectToAction("UserRoles", new { id = userrole.UserId });
        }

        public IActionResult AddRole(IdentityUserRole<string> userrole)
        {
            //var role = context.Roles.Where(z => z.Name == "Client").Single();
            //IdentityUserRole<string> userrole = new IdentityUserRole<string>();
            //userrole.UserId = id;
            //userrole.RoleId = role.Id;
            //context.UserRoles.Add(userrole);
            //context.SaveChanges();
            context.UserRoles.Add(userrole);
            context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
    }
}

src/Teleoffice/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Teleoffice.Models;
// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Teleoffice.Controllers
{
    //[Authorize(Roles = "Administrator")]
    public class RoleController : Controller
    {
        private ApplicationDbContext context;

        public RoleController(ApplicationDbContext _context)
        {
            context = _context;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            var roles = context.Roles.OrderBy(r => r.Name).ToList();
            return View(roles);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(IdentityRole role)
        {
            try
            {
                context.Roles.Add(new Microsoft.AspNet.Identity.EntityFramework.IdentityRole()
                {
                    Name = role.Name
                });
                context.SaveChanges();
                ViewBag.ResultMessage = "Role created successfully !";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }

        }

        public IActionResult DeleteRole(string name)
        {
            var role = context.Roles.Where(z => z.Name == name).Single();
            context.Roles.Remove(role);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/Teleoffice/Views/Role/Create.cshtml
@using Teleoffice.Models
@using Microsoft.AspNet.Identity.EntityFramework
@model IdentityRole

@{
    ViewData["Title"] = "Create Role";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<form asp-controller="Role" asp-action="Create" method="post">
    <div class="form-group">
        <label for="DisplayName">Name</label>
        <input asp-for="Name" class="form-control" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <button class="btn btn-default btn-primary">Save</button>
</form>

src/Teleoffice/Views/Role/Index.cshtml
@using Teleoffice.Models
@using System.Collections.Generic
@using Microsoft.AspNet.Identity.EntityFramework
@model IEnumerable<IdentityRole>

@{
    ViewData["Title"] = "List of roles";
}

@if (Model.Count() != 0)
{
    <h2>Administrative Page</h2>
    <h3> All Roles </h3><br>
    <table class="table table-striped">
       
        @{
            
            int count = 1;
        }

        @foreach (var role in Model)
        {
                <tr>
                    <td>@count</td>
                    <td>@role.Name</td>
                    <td>
                        <br>@Html.ActionLink("Delete", "DeleteRole", "Role", new { name = @role.Name }, new { @class = "btn btn-danger"})
                    </td>
                    
                </tr>
                count = count + 1;
         }
        
                <tr>
            @*<td>
                <button type="button" class="btn btn-primary"><a asp-controller="Role" asp-action="Create" method="post" style="color:white;">Add Roles</a></button>
            </td>*@
                    <td><br>
                        @Html.ActionLink("Add Roles", "Create", "Role", new { id = "none" }, new { @class = "btn btn-primary" })
                    </td>
                    <td><br />
                         @Html.ActionLink("Manage Users", "Index", "ManageUser", new { id = "none"}, new { @class = "btn btn-primary" })
                    </td>
            
               </tr>
    </table>
}

<br>
<div class="panel"  style="height:50px;">
    @Html.ActionLink("View Feedbacks from clients", "ViewFeedbacks", "Home", new { id = "None" }, new { @class = "link" })
</div>