src/Teleoffice/ViewModels/Client/AppUserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Teleoffice.ViewModels
{
    public class AppUserViewModel
    {
        public String FName { get; set; }
        public String LName { get; set; }
        public String Subject { get; set; }
        public DateTime MeetTime { get; set; }
        public int AppId { get; set; }

    }
}

src/Teleoffice/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Teleoffice.Models;
using Microsoft.AspNet.Authorization;
using Teleoffice.ViewModels.Client;
using System.Security.Claims;
using Microsoft.Data.Entity.Internal;

namespace Teleoffice.Controllers
{
    [Authorize(Roles = "Client")]
    public class ClientController: Controller
    {
        private ApplicationDbContext context;

        public ClientController(ApplicationDbContext _context)
        {
            context = _context;
        }
        
        //Get
        public IActionResult Index()
        {
            //dynamic dy = new ExpandoObject();
            ViewBag.user = context.Users.Where(z => z.Id == User.GetUserId()).Single();
            ViewBag.notify = context.Notifications.Where(z => z.UserId == User.GetUserId() && z.Read == 0).ToList();
            var role = context.Roles.Where(z => z.Name == "Professional").Single();
            var userroles = context.UserRoles.Where(z => z.RoleId == role.Id).ToList();
            List<ApplicationUser> prousers = new List<ApplicationUser>();
            if (userroles.Count > 0)
            {
                foreach (var ur in userroles)
                {
                    var tu = context.Users.Where(u => u.Id == ur.UserId).Single();
                    prousers.Add(tu);
                }

            }
            ViewBag.pros = prousers;

            //var role1 = context.Roles.Where(z => z.Name == "Assistant").Single();
            //var userroles1 = context.UserRoles.Where(z => z.RoleId == role.Id).ToList();
            //List<ApplicationUser> prousers1 = new List<ApplicationUser>();
            //if (userroles1.Count > 0)
            //{
            //    foreach (var ur in userroles1)
            //    {
            //        var tu = context.Users.Where(u => u.Id == ur.UserId).Single();
            //        prousers1.Add(tu);
            //    }

            //}
            //ViewBag.assist = prousers1;

            var apt = (from a in context.Appointments
                       join ft in context.Users on a.ProfessionalId equals ft.Id
                       where a.IsValid == 1 && a.ClientId == User.GetUserId()
                       select new AppUserViewModel { FName = ft.FirstName, LName = ft.LastName, Subject = a.Subject, MeetTime = a.MeetingTime, AppId = a.Id }).ToList();
                                     
            return View("Index", apt);
            
        }

        //Get//create appointments
        [HttpGet]
        public IActionResult CreateAppointment(String ProfId)
        {
            //dynamic dy = new ExpandoObject();
            ViewBag.user = context.Users.Where(z => z.Id == User.GetUserId()).Single();
            ViewBag.client = context.Users.Where(z => z.Id == User.GetUserId()).Single();
            ViewBag.prof = context.Users.Where(z => z.Id == ProfId).Single();
            return View();

        }

        //post//submit appointments

        [HttpPost]
        public IActionResult CreateAppointment(Appointment app)
        {
            //dynamic dy = new ExpandoObject();

            context.Appointments.Add(new Appointment
            {
                Subject = app.Subject,
                Message = app.Message,
                MeetingTime = app.MeetingTime,
                ClientId = app.ClientId,
                ProfessionalId = app.ProfessionalId,
                IsValid = 0    //1 after it is confirmed, 2 when declined
                
               
            });
            context.SaveChanges();
            var client = context.Users.Where(u => u.Id == app.ClientId).Single();
            var prof = context.Users.Where(u => u.Id == app.ProfessionalId).Single();
            //var id = context.Appointments.Last();
            
            //notification for client
            Notification n = new Notification();            
            n.Message = "You requested an appointment with " + prof.FirstName + " " + prof.LastName + " on " + app.MeetingTime;
            n.ReceivedTime = DateTime.Now;
            n.UserId = client.Id;
            n.Read = 0;
            n.Status = 1;
            //n.IsApproved = 0;
            //n.AppointmentId = id.Id;

            //notification for prof
            Notification m = new Notification();
            m.Message = client.FirstName + " " + client.LastName + "  requested an appointment with you on " + app.MeetingTime;
            m.ReceivedTime = DateTime.Now;
            m.UserId = prof.Id;
            m.Read = 0;
            m.Status = 1;
            //m.IsApproved = 0;
            //m.AppointmentId = id.Id;

            context.Notifications.Add(n);
            context.Notifications.Add(m);
            context.SaveChanges();

            NotifyApp an = new NotifyApp();
            var appid = context.Appointments.Last();
            an.AppointmentId = appid.Id;
            an.ClientNotificationId = n.Id;
            an.ProfNotificationId = m.Id;
            context.NotifyApps.Add(an);
            context.SaveChanges();
            return RedirectToAction("Index");

        }

        public IActionResult Agree(int id)
        {
            var notifyapp = context.NotifyApps.Where(z => z.ClientNotificationId == id).Single();
            var appuser = context.Appointments.Where(z => z.Id == notifyapp.AppointmentId).Single();
            var client = context.Users.Where(z => z.Id == appuser.ClientId).Single();
            var prof = context.Users.Where(z => z.Id == appuser.ProfessionalId).Single();

            appuser.IsValid = 1; // agreed on prof's demand
            context.Appointments.Update(appuser);

            var n = context.Notifications.Where(z => z.Id == id).Single();
            n.Message = "You confirmed an appointment with " + prof.FirstName + " " + prof.LastName;
            n.ReceivedTime = DateTime.Now;
            n.Status = 2;

            var m = context.Notifications.Where(z => z.Id == id).Single();
            m.Message = client.FirstName + " " + client.LastName + "confirmed appointment with you";
            m.ReceivedTime = DateTime.Now;
            m.Status = 2;

            context.Notifications.Update(n);
            context.Notifications.Update(m);
            context.SaveChanges();
            
            return RedirectToAction("Index");
        }

        public IActionResult RequestAgain(int id)
        {
            var notifyapp = context.NotifyApps.Where(z => z.ClientNotificationId == id).Single();
            var appuser = context.Appointments.Where(z => z.Id == notifyapp.AppointmentId).Single();
            var prof = context.Users.Where(z => z.Id == appuser.ProfessionalId).Single();
            return RedirectToAction("CreateAppointment", new { ProfId = prof.Id });
        }

        public IActionResult ViewAppointments()
        {
            ViewBag.app = context.Appointments.Where(z => z.IsValid == 1).ToList();
            ViewBag.user = context.Users.Where(u => u.Id == User.GetUserId()).Single();
            ViewBag.notify = context.Notifications.Where(n => n.UserId == User.GetUserId() && n.Read == 0).ToList();

            var apt = (from a in context.Appointments
                       join ft in context.Users on a.ProfessionalId equals ft.Id
                       where (a.IsValid == 1 || a.IsValid == 3) && a.ClientId == User.GetUserId()
                       select new AppUserViewModel { FName = ft.FirstName, LName = ft.LastName, Subject = a.Subject, MeetTime = a.MeetingTime, AppId = a.Id }).ToList();

            return View("ViewAppointments", apt);
        }

        public IActionResult NotificationDetail(int id)
        {
            ViewBag.user = context.Users.Where(u => u.Id == User.GetUserId()).Single();
            ViewBag.notify = context.Notifications.Where(z => z.Id == id).Single();
            var notifyapp = context.NotifyApps.Where(z => z.ClientNotificationId == id).Single();
            ViewBag.app = context.Appointments.Where(z => z.Id == notifyapp.AppointmentId).Single();
            return View();
        }
        public IActionResult CallRate()
        {
            ViewBag.callrate = context.Users.Where(z => z.CallRate != 0).ToList();
            return View();
        }

    }
}

src/Teleoffice/Controllers/NotificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Teleoffice.Models;
using Microsoft.AspNet.Authorization;
using System.Security.Claims;
using System.Dynamic;

namespace Teleoffice.Controllers
{
    [Authorize]
    public class NotificationController: Controller

    {
        private ApplicationDbContext context;

        public NotificationController(ApplicationDbContext _context)
        {
            context = _context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public Boolean Read(int id)
        {
            Notification notify = context.Notifications.Where(z => z.Id == id).Single();
            notify.Read = 1;
            context.Notifications.Update(notify);
            context.SaveChanges();
            return true;
        }

    }
}

src/Teleoffice/Controllers/VideoCallController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Teleoffice.Models;
using System.Security.Claims;
using System.Dynamic;
// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Teleoffice.Controllers
{
    //[Authorize(Roles = "Client")]
    //[Authorize(Roles = "Professional")]
    public class VideoCallController : Controller
    {
        private ApplicationDbContext context;

        public VideoCallController(ApplicationDbContext _context)
        {
            context = _context;
        }
        // GET: /<controller>/
        public IActionResult Index(int Id)
        {
            dynamic dy = new ExpandoObject();
            var apt = context.Appointments.Where(z => (z.IsValid == 1 || z.IsValid == 2 || z.IsValid == 3) && z.Id == Id).Single();
            var usrrole1 = context.UserRoles.Where(z => z.UserId == User.GetUserId()).Single();
            dy.usrrole = usrrole1;

            var role1 = context.Roles.Where(z => z.Name == "Client").Single();
            dy.role = role1;
            var role2 = context.Roles.Where(z => z.Name == "Professional").Single();
            
            dy.id = Id;
            dy.client = context.Users.Where(z => z.Id == apt.ClientId).Single();
            
            dy.prof = context.Users.Where(z => z.Id == apt.ProfessionalId).Single();
            dy.user = context.Users.Where(z => z.Id == User.GetUserId()).Single();
            dy.app = apt;
            if (usrrole1.RoleId == role1.Id)
            {
                apt.IsValid = 2;
                context.Appointments.Update(apt);
                context.SaveChanges();
            }
            if (usrrole1.RoleId == role2.Id)
            {
                apt.IsValid = 3;
                context.Appointments.Update(apt);
                context.SaveChanges();
            }

            return View(dy);
        }

        public IActionResult Call(int id)
        {
            var apt = context.Appointments.Where(z => z.IsValid == 1 && z.Id == id).Single();
            ViewBag.app = apt;
            return View();
        }
    }
}

src/Teleoffice/Views/Client/CallRate.cshtml
@using Teleoffice.Models


@{
    ViewData["Title"] = "Client";
}
<br>
<h3>Details of Professionals</h3>
<br>
<div class="row">
    <div class="col-sm-7">
        <div class="panel panel-default">
            <div class="panel-body">
                                @if (ViewBag.CallRate.Count > 0)
                                {
                                    <ul class="list-group">

                                        @foreach (var n in ViewBag.CallRate)
                                        {
                                            <li class="list-group-item call">
                                                <div class="row">
                                                    <div class="col-sm-10">
                                                      Name:   @n.FirstName @n.LastName<br>
                                                      Email:  @n.Email <br>
                                                      Contact No.  @n.Contact<br>
                                                      Fees( Charges per Hour):  Rs. @n.CallRate
                                                    </div>
                                                </div>
                                            </li>
                                        }
                                    </ul>
                                }
           </div>
     </div>
   </div>
</div>

src/Teleoffice/Views/Client/CreateAppointment.cshtml
@using Teleoffice.Models
@using Teleoffice.ViewModels.Client
@model AppUserViewModel

@{
    ViewData["Title"] = "Client";
}
<h3>Welcome @ViewBag.user.FirstName @ViewBag.user.LastName</h3>
<h4>Create new appointment with - @ViewBag.prof.FirstName @ViewBag.prof.LastName</h4>
<form asp-controller="Client" asp-action="CreateAppointment" method="post">
    <div class="form-group">
        <input hidden id="ProfessionalId" name="ProfessionalId" type="text" value="@ViewBag.prof.Id" />
        <input hidden id="ClientId" name="ClientId" type="text" value="@ViewBag.client.Id" />
        <label for="Subject">Subject</label>
        <input asp-for="Subject" name="Subject" class="form-control" />
        <label for="Message">Message</label>
        <textarea asp-for="Message" class="form-control"></textarea>
        <label for="MeetingTime">Date Time</label>
        <input asp-for="MeetTime" name="MeetingTime" class="form-control" placeholder="00-00-0000 00:00:00 am" />
    </div>
    <button class="btn btn-default btn-primary">Submit</button>
</form>

src/Teleoffice/Views/Client/Index.cshtml
@using Teleoffice.Models


@{
    ViewData["Title"] = "Client";
}
<br>
<h3>Welcome @ViewBag.user.FirstName @ViewBag.user.LastName</h3><br>

<div class="row">
    <div class="col-sm-7">
        
        <div class="panel panel-default">
            <div class="panel-body">

                
    @Html.ActionLink("View Your Appointments", "ViewAppointments", "Client", new { id = "None"}, new { @class = "btn btn-default" })
                </div>
            </div>

        <div><br>
        <h4>    @Html.ActionLink("View details about Professionals of this firm", "CallRate", "Client", new { id = "None" }, new { @class = "link" })</h4>
        </div><br><br><br>

                                       <form asp-controller="Client" asp-action="CreateAppointment" method="get">
                                                    <div class="form-group">
                                                        <label for="ProfessionalId">Want to book appointment with Professional?</label>
                                                        <select class="form-control" name="ProfId">
                                                            @foreach (var pro in ViewBag.pros)
                                                                {
                                                                <option value="@pro.Id">@pro.FirstName @pro.LastName</option>

                                                            }
                                                        </select>
                                                    </div>
                                                    <button class="btn btn-default btn-primary">Book Appointment</button>
                                                </form><br><br>

        @*<form asp-controller="Client" asp-action="CreateAppointment" method="get">
            <div class="form-group">
                <label for="ProfessionalId">Want to book appointment with Assistant?</label>
                <select class="form-control" name="ProfId">
                    @foreach (var ast in ViewBag.assist)
                    {
                        <option value="@ast.Id">@ast.FirstName @ast.LastName</option>

                    }
                </select>
            </div>
            <button class="btn btn-default btn-primary">Book Appointment</button>
        </form>*@
       
</div>

    

    <div class="col-sm-5">
        <div class="panel panel-default">
            <div class="panel-heading">Notifications</div>
            <div class="panel-body">
                @if (ViewBag.notify.Count > 0)
            {
                    <ul class="list-group">

                        @foreach (var n in ViewBag.notify)
                {
                            <li class="list-group-item notification-li">                                
                                    <div class="row">
                                        <div class="col-sm-10">
                                            @Html.ActionLink((string)@n.Message, "NotificationDetail", "Client", new { id = @n.Id }, new { @class = "detail" })
                                            <br><em>@n.ReceivedTime</em>
                                        </div>
                                        <div class="col-sm-2">
                                            @Html.ActionLink("X", "Read", "Notification", new { id = @n.Id }, new { @class = "btn btn-default notification-read" })
                                        </div>
                                    </div>                      
                            </li>
                        }
                    </ul>
                }
                else {
                    <p class="text-center">No new notification!</p>

                }
                @*@Html.ActionLink("View All", "Index", "Notification", new { id = "None" }, new { @class = "btn btn-default" })*@

            </div>
        </div>

    </div>

</div>

src/Teleoffice/Views/Client/NotificationDetail.cshtml
@using Teleoffice.Models

@{
    ViewData["Title"] = "Client";
}
<h3>Welcome @ViewBag.user.FirstName @ViewBag.user.LastName</h3>
<br>
<div class="col-sm-12">
    <div class="panel panel-default">
        <div class="panel-body">

        @ViewBag.notify.Message<br><br>
        Subject: @ViewBag.app.Subject<br><br>
        Description: @ViewBag.app.Message<br><br>
        Meeting Time: @ViewBag.app.MeetingTime<br>
        <br>

        @if (ViewBag.app.IsValid == 2)
        {
            <div class="col-sm-4">
                <br>@Html.ActionLink("Agree", "Agree", "Client", new { id = ViewBag.notify.Id }, new { @class = "btn btn-default" })
            </div>
            <div class="col-sm-4">
                 @Html.ActionLink("Request Again", "RequestAgain", "Client", new { id = ViewBag.notify.Id }, new { @class = "btn btn-primary" })
               </div>
                 }
           </div>
        </div>
    </div>

src/Teleoffice/Views/Client/ViewAppointments.cshtml
@using Teleoffice.Models
@using Teleoffice.ViewModels.Client
@model IEnumerable<AppUserViewModel>

@{
    ViewData["Title"] = "Client";
}
<h3>Welcome @ViewBag.user.FirstName @ViewBag.user.LastName</h3>

<div class="row">
    <div class="col-sm-7">
        <h4>Your Appointments</h4><br>
        @if (Model.Count() > 0)
        {
            <ul class="list-group">

                @foreach (var p in Model)
                {
                    <li class="list-group-item notif">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel-default">
                                    <div class="panel-heading">You have an appointment with @p.FName @p.LName</div><br>
                                    <b>Subject:</b> @p.Subject<br />
                                    <b>Meeting Time:</b> @p.MeetTime<br><br>
                                    @Html.ActionLink("Attend", "Index", "VideoCall", new { id = @p.AppId }, new { @class = "btn btn-success" })
                                </div>
                                </div>
                        </div>
                    </li>
                }

            </ul>
        }
        else {
            <div class="panel panel-default">
                <div class="panel-body">
                    No appointments found
                </div>
            </div>
        }
    </div>
</div>